#!/usr/bin/env python3
"""Generate lightweight API reference markdown for Caveman (#31)."""
from __future__ import annotations

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "caveman"
OUTPUT = ROOT / "docs" / "API_REFERENCE.md"


def public_members(path: Path) -> tuple[list[str], list[str]]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    classes: list[str] = []
    functions: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            classes.append(node.name)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
            functions.append(node.name)
    return classes, functions


def module_doc(path: Path) -> str:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except SyntaxError:
        return ""
    doc = ast.get_docstring(tree) or ""
    return " ".join(doc.split())[:220]


def main() -> int:
    lines = [
        "# Caveman API Reference",
        "",
        "> Auto-generated by `scripts/generate_api_reference.py`. Do not edit by hand.",
        "",
    ]
    for path in sorted(PACKAGE.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        rel = path.relative_to(ROOT)
        module = ".".join(rel.with_suffix("").parts)
        classes, functions = public_members(path)
        doc = module_doc(path)
        if not doc and not classes and not functions:
            continue
        lines.append(f"## `{module}`")
        lines.append("")
        if doc:
            lines.append(doc)
            lines.append("")
        if classes:
            lines.append("**Classes:** " + ", ".join(f"`{c}`" for c in classes))
            lines.append("")
        if functions:
            lines.append("**Functions:** " + ", ".join(f"`{f}()`" for f in functions))
            lines.append("")
    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Generated {OUTPUT} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
